#+hugo_base_dir: .
#+language: it
#+options: author:nil
#+startup: logdone

* DONE Pagina di prova :test:katex:inkscape:
CLOSED: [2022-02-20 dom 20:38]
:PROPERTIES:
:EXPORT_FILE_NAME: pagina-di-prova
:END:
#+begin_description
In modalità org l'introduzione al post è inserita all'interno del blocco =description= ed esportata nel front matter del file markdown processato da Hugo.
#+end_description
** Formule
In tutte le pagine [[https://katex.org][$\KaTeX$]] si occupa del rendering delle formule matematiche, sia /inline/ come ad esempio l'identità di Eulero $e^{i\pi} = -1$, sia a centro pagina come nella definizione della funzione zeta di Riemann
\[
\zeta(s) = \sum_{i = 1}^{\infty} \frac{1}{n^s}
\]
** Immagini SVG
Quasi tutte le immagini sono create con [[https://inkscape.org/it/][Inkscape]] e salvate nel formato svg nativo: per inserire le formule in $\LaTeX$ c'è l'ottima estensione TexText.[fn:1]

[[/images/gauss.svg]]

Il preambolo a cui TexText fa riferimento è semplicemente
#+begin_src tex
\documentclass[12pt]{article}
\usepackage{amsmath,amsthm,amssymb,amsfonts}
\usepackage{color}
#+end_src
L'opzione della classe =article= emula i 16 pixel del testo nella pagina. Inoltre in TexText è impostato un fattore di scala di =1.21em=, per cui l'effetto dovrebbe essere quello di avere formule della stessa dimensione in html che in svg.[fn:2]

La prima è un'immagine svg, mentre la seconda è generata con KaTeX.

[[/images/zeta.svg]]

\[\zeta(s) = \prod_p \frac{1}{1 - p^{-s}}\]
** Spell checker
Doom Emacs non offre una configurazione dedicata per Ispell in modalità org. Almeno per saltare il controllo dei blocchi con formule si può usare il codice seguente nella propria configurazione:
#+begin_src elisp
(add-hook 'org-mode-hook
          (lambda ()
            (make-local-variable 'ispell-skip-region-alist)
            (add-to-list 'ispell-skip-region-alist '("\\\\\\[" . "\\\\]"))
            (add-to-list 'ispell-skip-region-alist '("\\$" . "\\$"))
            ))
#+end_src
** Tabelle
Org permette molto agevolmente di costruire tabelle in testo semplice: lo stile delle tabella seguente è adattato dal [[https://github.com/gwgundersen/blog-theme/blob/master/css/blog.css][blog di Gregory Gundersen]]. Il numero di soluzioni reali dell'equazione $ax^2 + bx + c = 0$ dipende dal segno del *discriminante* \[\Delta = b^2 - 4ac\] definito a partire dai coefficienti $a$, $b$ e $c$ come riepilogato nella tabella seguente:

| Segno di $\Delta$ | Soluzioni reali           | Soluzioni puramente immaginarie |
|-------------------+---------------------------+---------------------------------|
| $\Delta > 0$      | Due                       | Nessuna                         |
| $\Delta = 0$      | Una soltanto              | Nessuna                         |
| $\Delta < 0$      | Nessuna                   | Due (opposte)                   |

Nel caso in cui $\Delta \geq 0$ vale la formula risolutiva per le equazioni di secondo grado
\[
x = \frac{-b \pm \sqrt{\Delta}}{2a}
\]
Come per le figure, è possibile aggiungere una didascalia alle tabelle utilizzando il tag =#+caption= in org-mode.
** Liste :list:
In Org-mode è possibile attribuire un tag (o anche più di uno) a ciascuna sezione del post. Tuttavia, questi non sono cliccabili. Ad esempio, al titolo di questo paragrafo è stato aggiunto il tag =list=.

I corpi considerati in fisica possono essere di diversa natura.
- Corpi /puntiformi/: dotati di massa ma aventi volume zero (considerati cioè come un punto che non occupa una regione estesa di spazio)
- Corpi /estesi/: aventi sia massa che volume positivi
Finora abbiamo trattato
#+attr_html: :class task-list
- [X] Corpi puntiformi
- [ ] Corpi estesi
La sintassi di Org per creare le cosiddette /TODO list/ è la stessa di Markdown. Attenzione al fatto che la classe ~task-list~ non è automaticamente esportata[fn:3] in Black Friday, ed è pertanto necessario indicarla esplicitamente all'inizio della lista, ad esempio con
#+begin_src org
,#+ attr_html: :class task-list
- [X] Corpi puntiformi
- [ ] Corpi estesi
#+end_src
In questo modo è possibile ad esempio rimuovere i pallini prima di ciascun elemento impostando lo stile nel file css.
* DONE Integrazione con Telegram
CLOSED: [2022-03-20 dom 19:50]
:PROPERTIES:
:EXPORT_FILE_NAME: telegram-trigger
:END:
#+begin_description
Un bot che notifica un canale Telegram a ogni nuovo post pubblicato.
#+end_description
Creato canale Telegram con [[https://t.me/+QcNUYOHdOPxlYWVk][invite link]] (le richieste vanno approvate dagli admin). L'idea è creare un bot da zero che sia in grado di
1. notificare il canale di ogni nuovo contenuto pubblicato sul sito;
2. gestire i commenti degli utenti.

Una soluzione al primo punto è offerta da [[https://ifttt.com/][IFTTT]] che consente all'applicazione di puntare al file [[https://tizero.github.io/org-notes/index.xml][index.xml]] e di connettersi a una chat di gruppo o a un canale. Il secondo punto può essere ottenuto direttamente con le funzionalità di Telegram associando al canale una chat dedicata.
* Footnotes
[fn:1] Reperibile al link [[https://textext.github.io/textext/]]
[fn:2] Il fattore di scala =1.21em= è il default di KaTeX ([[https://katex.org/docs/font.html#font-size-and-lengths][docs]])
[fn:3] Vedi [[https://github.com/gohugoio/hugo/issues/6837][hugo issue 6837]]
* COMMENT Local Variables :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
