baseURL = "https://tizero.github.io/org-notes"
defaultContentLanguage = "it"
title = "Org notes"

canonifyURLs = true

enableEmoji = true
enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  custom_css = ["css/style.css"]
  favicon = """
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/png" href="/favicon.png">
"""

  [Params.source]
    url = "https://github.com/tiZero/org-notes"
    md_dir = "content"

[markup.goldmark.rederer]
  unsafe = true
