baseURL = "http://example.org/"
defaultContentLanguage = "it"
title = "Org notes"

enableEmoji = true
enableGitInfo = true

[Params]
  disable_debug = true
  custom_css = ["css/style.css"]
  favicon = """
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/png" href="/favicon.png">
"""

[markup.goldmark.rederer]
  unsafe = true
